In [1]:
import pandas as pd

In [2]:
data = {
    'Transaction ID': [101, 102, 103, 103, 104, 105, 106],
    'Customer Name': ['Harry Potter', 'Hermione Granger', 'Ron Weasley', 'Ron Weasley', 'Draco Malfoy', 'Luna Lovegood', 'Draco Malfoy'],
    'Wand': ['Elder Wand', 'Vine Wood', 'Hawthorn', 'Hawthorn', 'Dragon Heartstring', 'Thestral Tail Hair', 'Dragon Heartstring'],
    'Price': [100, 75, 50, 50, 80, 60, 80]
}

Wand_Transactions = pd.DataFrame(data)

Wand_Transactions

   Transaction ID     Customer Name                Wand  Price
0             101      Harry Potter          Elder Wand    100
1             102  Hermione Granger           Vine Wood     75
2             103       Ron Weasley            Hawthorn     50
3             103       Ron Weasley            Hawthorn     50
4             104      Draco Malfoy  Dragon Heartstring     80
5             105     Luna Lovegood  Thestral Tail Hair     60
6             106      Draco Malfoy  Dragon Heartstring     80

In [3]:
Wand_Transactions.drop_duplicates()

   Transaction ID     Customer Name                Wand  Price
0             101      Harry Potter          Elder Wand    100
1             102  Hermione Granger           Vine Wood     75
2             103       Ron Weasley            Hawthorn     50
4             104      Draco Malfoy  Dragon Heartstring     80
5             105     Luna Lovegood  Thestral Tail Hair     60
6             106      Draco Malfoy  Dragon Heartstring     80

In [4]:
data = {
    'First Name': ['Harry', 'Hermione', 'Ron', 'Harry', 'Draco', 'Luna', 'Harry'],
    'Last Name': ['Potter', 'Granger', 'Weasley', 'Potter', 'Malfoy', 'Lovegood', 'Potter'],
    'Hogwarts House': ['Gryffindor', 'Gryffindor', 'Gryffindor', 'Gryffindor', 'Slytherin', 'Ravenclaw', 'Gryffindor'],
    'Favorite Class': ['Defense Against the Dark Arts', 'Potions', 'Charms', 'Quidditch', 'Transfiguration', 'Care of Magical Creatures', 'Herbology']
}

Class_List = pd.DataFrame(data)

Class_List

  First Name Last Name Hogwarts House                 Favorite Class
0      Harry    Potter     Gryffindor  Defense Against the Dark Arts
1   Hermione   Granger     Gryffindor                        Potions
2        Ron   Weasley     Gryffindor                         Charms
3      Harry    Potter     Gryffindor                      Quidditch
4      Draco    Malfoy      Slytherin                Transfiguration
5       Luna  Lovegood      Ravenclaw      Care of Magical Creatures
6      Harry    Potter     Gryffindor                      Herbology

In [5]:
Class_List.drop_duplicates(subset = ['First Name','Last Name'])

  First Name Last Name Hogwarts House                 Favorite Class
0      Harry    Potter     Gryffindor  Defense Against the Dark Arts
1   Hermione   Granger     Gryffindor                        Potions
2        Ron   Weasley     Gryffindor                         Charms
4      Draco    Malfoy      Slytherin                Transfiguration
5       Luna  Lovegood      Ravenclaw      Care of Magical Creatures

In [8]:
Class_List.drop_duplicates(subset = ['First Name','Last Name'], keep = 'last')

  First Name Last Name Hogwarts House             Favorite Class
1   Hermione   Granger     Gryffindor                    Potions
2        Ron   Weasley     Gryffindor                     Charms
4      Draco    Malfoy      Slytherin            Transfiguration
5       Luna  Lovegood      Ravenclaw  Care of Magical Creatures
6      Harry    Potter     Gryffindor                  Herbology

In [6]:
data = {
    'student_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'full_name': ['Harry Potter', 'Hermione Granger', 'Ron Weasley', 'Draco Malfoy', 'Luna Lovegood', 'Neville Longbottom', 'Ginny Weasley', 'Fred Weasley', 'George Weasley', 'Cho Chang'],
    'phone_number': ['(123) 456-7890', '555-123-4567', '9876543210', '123.456.7890', '(123)-4567890', '987-654-3210', '123 456 7890', '1234567890', '+7890123456', '012-345-6789']
}

Bad_Numbers = pd.DataFrame(data)
Bad_Numbers

   student_id           full_name    phone_number
0           1        Harry Potter  (123) 456-7890
1           2    Hermione Granger    555-123-4567
2           3         Ron Weasley      9876543210
3           4        Draco Malfoy    123.456.7890
4           5       Luna Lovegood   (123)-4567890
5           6  Neville Longbottom    987-654-3210
6           7       Ginny Weasley    123 456 7890
7           8        Fred Weasley      1234567890
8           9      George Weasley     +7890123456
9          10           Cho Chang    012-345-6789

In [16]:
Bad_Numbers['phone_number'] = Bad_Numbers['phone_number'].str.replace(r'\D','',regex = True)

In [17]:
Bad_Numbers

   student_id           full_name phone_number
0           1        Harry Potter   1234567890
1           2    Hermione Granger   5551234567
2           3         Ron Weasley   9876543210
3           4        Draco Malfoy   1234567890
4           5       Luna Lovegood   1234567890
5           6  Neville Longbottom   9876543210
6           7       Ginny Weasley   1234567890
7           8        Fred Weasley   1234567890
8           9      George Weasley   7890123456
9          10           Cho Chang   0123456789

In [18]:
len(Bad_Numbers[Bad_Numbers['phone_number'].str.len() != 10])

0

In [19]:
Bad_Numbers['phone_number'] = Bad_Numbers['phone_number'].str[:3] + '-' + Bad_Numbers['phone_number'].str[3:6] + '-' + Bad_Numbers['phone_number'].str[6:]

In [20]:
Bad_Numbers

   student_id           full_name  phone_number
0           1        Harry Potter  123-456-7890
1           2    Hermione Granger  555-123-4567
2           3         Ron Weasley  987-654-3210
3           4        Draco Malfoy  123-456-7890
4           5       Luna Lovegood  123-456-7890
5           6  Neville Longbottom  987-654-3210
6           7       Ginny Weasley  123-456-7890
7           8        Fred Weasley  123-456-7890
8           9      George Weasley  789-012-3456
9          10           Cho Chang  012-345-6789

In [21]:
data = {
    'Full Name': ['Harry Potter', 'Hermione Granger', 'Ron Weasley', 'Draco Malfoy', 'Luna Lovegood', 'Gregory Goyle'],
    'Voldemort_Bad': ['Y', 'Yes', 'Yes', 'No', 'yes', 'Nope!']
}

Voldy = pd.DataFrame(data)

Voldy

          Full Name Voldemort_Bad
0      Harry Potter             Y
1  Hermione Granger           Yes
2       Ron Weasley           Yes
3      Draco Malfoy            No
4     Luna Lovegood           yes
5     Gregory Goyle         Nope!

In [24]:
Voldy['Voldemort_Bad'] = Voldy['Voldemort_Bad'].apply(lambda x: 'Yes' if x.startswith(('Y','y')) else ('No' if x.startswith(('N','n')) else x))

In [25]:
Voldy

          Full Name Voldemort_Bad
0      Harry Potter           Yes
1  Hermione Granger           Yes
2       Ron Weasley           Yes
3      Draco Malfoy            No
4     Luna Lovegood           Yes
5     Gregory Goyle            No

In [26]:
data = {
    'First Name': ['Harry', 'Hermione', 'Ron', 'Hermione', 'Ronald', 'Harry', 'Hermion', 'Ron'],
    'Last Name': ['Potter', 'Granger', 'Weasley', 'Grangar', 'Weasly', 'Poter', 'Graner', 'Weaseley'],
    'Age': [18, 17, 18, 17, 18, 18, 17, 18],
    'Social Security Number': ['123-45-6789', '987-65-4321', '555-55-5555', '987-65-4321', '555-55-5555',
                               '123-45-6789', '987-65-4321', '555-55-5555']
}

Hogwarts_Students = pd.DataFrame(data)

In [28]:
Hogwarts_Students['Same Student ID'] = Hogwarts_Students.groupby('Social Security Number').ngroup()

In [29]:
Hogwarts_Students

  First Name Last Name  Age Social Security Number  Same Student ID
0      Harry    Potter   18            123-45-6789                0
1   Hermione   Granger   17            987-65-4321                2
2        Ron   Weasley   18            555-55-5555                1
3   Hermione   Grangar   17            987-65-4321                2
4     Ronald    Weasly   18            555-55-5555                1
5      Harry     Poter   18            123-45-6789                0
6    Hermion    Graner   17            987-65-4321                2
7        Ron  Weaseley   18            555-55-5555                1

In [30]:
Hogwarts_Students.groupby('Same Student ID')['Social Security Number'].count()

Same Student ID
0    2
1    3
2    3
Name: Social Security Number, dtype: int64

In [31]:
Hogwarts_Students['Sub string'] = Hogwarts_Students['First Name'].str[:3] + Hogwarts_Students['Last Name'].str[:3]

In [32]:
Hogwarts_Students

  First Name Last Name  Age Social Security Number  Same Student ID Sub string
0      Harry    Potter   18            123-45-6789                0     HarPot
1   Hermione   Granger   17            987-65-4321                2     HerGra
2        Ron   Weasley   18            555-55-5555                1     RonWea
3   Hermione   Grangar   17            987-65-4321                2     HerGra
4     Ronald    Weasly   18            555-55-5555                1     RonWea
5      Harry     Poter   18            123-45-6789                0     HarPot
6    Hermion    Graner   17            987-65-4321                2     HerGra
7        Ron  Weaseley   18            555-55-5555                1     RonWea

In [33]:
Hogwarts_Students['New ID'] = Hogwarts_Students.groupby('Sub string').ngroup() + 1

In [34]:
Hogwarts_Students

,First Name,Last Name,Age,Social Security Number,Same Student ID,Sub string,New ID
0,Harry,Potter,18,123-45-6789,0,HarPot,1
1,Hermione,Granger,17,987-65-4321,2,HerGra,2
2,Ron,Weasley,18,555-55-5555,1,RonWea,3
3,Hermione,Grangar,17,987-65-4321,2,HerGra,2
4,Ronald,Weasly,18,555-55-5555,1,RonWea,3
5,Harry,Poter,18,123-45-6789,0,HarPot,1
6,Hermion,Graner,17,987-65-4321,2,HerGra,2
7,Ron,Weaseley,18,555-55-5555,1,RonWea,3

In [35]:
data = {
    'First Name': ['Harry', 'Hermione?', 'Ron', 'Hermione', 'Ron_', 'Harry!', 'Hermione', 'Ron'],
    'Last Name': ['"Potter"', 'Granger', 'Weasley', 'Granger', 'Weasley...', 'Potter', 'Granger', 'Weasley'],
    'Age': [18, 17, 18, 17, 18, 18, 17, 18]
}

Hogwarts_Students2 = pd.DataFrame(data)

Hogwarts_Students2

  First Name   Last Name  Age
0      Harry    "Potter"   18
1  Hermione?     Granger   17
2        Ron     Weasley   18
3   Hermione     Granger   17
4       Ron_  Weasley...   18
5     Harry!      Potter   18
6   Hermione     Granger   17
7        Ron     Weasley   18

In [37]:
Hogwarts_Students2['First Name'] = Hogwarts_Students2['First Name'].str.replace(r'[^a-zA-Z]','', regex = True)

In [38]:
Hogwarts_Students2['Last Name'] = Hogwarts_Students2['Last Name'].str.replace(r'[^a-zA-Z]','', regex = True)

In [39]:
Hogwarts_Students2

  First Name Last Name  Age
0      Harry    Potter   18
1   Hermione   Granger   17
2        Ron   Weasley   18
3   Hermione   Granger   17
4        Ron   Weasley   18
5      Harry    Potter   18
6   Hermione   Granger   17
7        Ron   Weasley   18

In [40]:
data = {
    'student_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'full_name': ['Harry Potter', 'Hermione Granger', 'Ron Weasley', 'Draco Malfoy', 'Luna Lovegood', 'Neville Longbottom', 'Ginny Weasley', 'Fred Weasley', 'George Weasley', 'Cho Chang'],
    'is_alive': ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes']
}

dead_or_alive = pd.DataFrame(data)
dead_or_alive

   student_id           full_name is_alive
0           1        Harry Potter      Yes
1           2    Hermione Granger      Yes
2           3         Ron Weasley      Yes
3           4        Draco Malfoy      Yes
4           5       Luna Lovegood      Yes
5           6  Neville Longbottom      Yes
6           7       Ginny Weasley      Yes
7           8        Fred Weasley       No
8           9      George Weasley      Yes
9          10           Cho Chang      Yes

In [42]:
dead_or_alive[['First Name','Last Name']] = dead_or_alive['full_name'].str.split(' ',expand = True)

In [43]:
dead_or_alive

   student_id           full_name is_alive First Name   Last Name
0           1        Harry Potter      Yes      Harry      Potter
1           2    Hermione Granger      Yes   Hermione     Granger
2           3         Ron Weasley      Yes        Ron     Weasley
3           4        Draco Malfoy      Yes      Draco      Malfoy
4           5       Luna Lovegood      Yes       Luna    Lovegood
5           6  Neville Longbottom      Yes    Neville  Longbottom
6           7       Ginny Weasley      Yes      Ginny     Weasley
7           8        Fred Weasley       No       Fred     Weasley
8           9      George Weasley      Yes     George     Weasley
9          10           Cho Chang      Yes        Cho       Chang

In [44]:
data = {
    'student_id': [1, 2, 3, 4, 5, 6, 7, 8, 9],
    'full_name': ['Harry Potter', 'Hermione Granger', 'Ron Weasley', 'Draco Malfoy', 'Luna Lovegood', 'Neville Longbottom', 'Ginny Weasley', 'Fred Weasley', 'George Weasley'],
    'address': ['12 Grimmauld Place, London, England', '4 Privet Drive, Surrey, England', 'The Burrow, Devon, England', '124 Slitheren Street, Wiltshire, England', '869 Light Way, London, England', '4834 Street, Hampshire, England', 'The Burrow, Devon, England', 'The Burrow, Devon, England', 'The Burrow, Devon, England']
}

Student_Address = pd.DataFrame(data)
Student_Address

   student_id           full_name                                   address
0           1        Harry Potter       12 Grimmauld Place, London, England
1           2    Hermione Granger           4 Privet Drive, Surrey, England
2           3         Ron Weasley                The Burrow, Devon, England
3           4        Draco Malfoy  124 Slitheren Street, Wiltshire, England
4           5       Luna Lovegood            869 Light Way, London, England
5           6  Neville Longbottom           4834 Street, Hampshire, England
6           7       Ginny Weasley                The Burrow, Devon, England
7           8        Fred Weasley                The Burrow, Devon, England
8           9      George Weasley                The Burrow, Devon, England

In [45]:
Student_Address[['Street','City','Country']] = Student_Address['address'].str.split(',',expand = True)

In [46]:
Student_Address

,student_id,full_name,address,Street,City,Country
0,1,Harry Potter,"12 Grimmauld Place, London, England",12 Grimmauld Place,London,England
1,2,Hermione Granger,"4 Privet Drive, Surrey, England",4 Privet Drive,Surrey,England
2,3,Ron Weasley,"The Burrow, Devon, England",The Burrow,Devon,England
3,4,Draco Malfoy,"124 Slitheren Street, Wiltshire, England",124 Slitheren Street,Wiltshire,England
4,5,Luna Lovegood,"869 Light Way, London, England",869 Light Way,London,England
5,6,Neville Longbottom,"4834 Street, Hampshire, England",4834 Street,Hampshire,England
6,7,Ginny Weasley,"The Burrow, Devon, England",The Burrow,Devon,England
7,8,Fred Weasley,"The Burrow, Devon, England",The Burrow,Devon,England
8,9,George Weasley,"The Burrow, Devon, England",The Burrow,Devon,England

In [47]:
data = {
    'First Name': ['Harry', 'Hermione', 'Ron', 'Draco', 'Luna', 'Neville', 'Ginny', 'Fred', 'George'],
    'Last Name': ['Potter', 'Granger', 'Weasley', 'Malfoy', 'Lovegood', 'Longbottom', 'Weasley', 'Weasley', 'Weasley'],
    'Hogwarts House': ['Gryffindor', 'Gryffindor', 'Gryffindor', 'Slytherin', 'Ravenclaw', 'Gryffindor', 'Gryffindor', 'Gryffindor', 'Gryffindor']
}

Combine_Names = pd.DataFrame(data)
Combine_Names

  First Name   Last Name Hogwarts House
0      Harry      Potter     Gryffindor
1   Hermione     Granger     Gryffindor
2        Ron     Weasley     Gryffindor
3      Draco      Malfoy      Slytherin
4       Luna    Lovegood      Ravenclaw
5    Neville  Longbottom     Gryffindor
6      Ginny     Weasley     Gryffindor
7       Fred     Weasley     Gryffindor
8     George     Weasley     Gryffindor

In [48]:
Combine_Names['Full Name'] = Combine_Names['First Name'] + ' ' + Combine_Names['Last Name']

In [49]:
Combine_Names

  First Name   Last Name Hogwarts House           Full Name
0      Harry      Potter     Gryffindor        Harry Potter
1   Hermione     Granger     Gryffindor    Hermione Granger
2        Ron     Weasley     Gryffindor         Ron Weasley
3      Draco      Malfoy      Slytherin        Draco Malfoy
4       Luna    Lovegood      Ravenclaw       Luna Lovegood
5    Neville  Longbottom     Gryffindor  Neville Longbottom
6      Ginny     Weasley     Gryffindor       Ginny Weasley
7       Fred     Weasley     Gryffindor        Fred Weasley
8     George     Weasley     Gryffindor      George Weasley

In [50]:
# or

pd.concat([Combine_Names['First Name'], Combine_Names['Last Name']], axis = 1).apply(' '.join, axis = 1)

0          Harry Potter
1      Hermione Granger
2           Ron Weasley
3          Draco Malfoy
4         Luna Lovegood
5    Neville Longbottom
6         Ginny Weasley
7          Fred Weasley
8        George Weasley
dtype: str

In [53]:
import numpy as np

In [54]:
data = {
    'First Name': ['Harry', 'Hermione', 'Ron', 'Draco', 'Luna', np.nan, np.nan],
    'Last Name': ['Potter', 'Granger', 'Weasley', 'Malfoy', np.nan, 'Lovegood', np.nan],
    'Hogwarts House': ['Gryffindor', 'Gryffindor', 'Gryffindor', np.nan, 'Ravenclaw', 'Gryffindor', np.nan],
    'Age': [18, 17, np.nan, 16, 16, 18, np.nan]
}

Nulls = pd.DataFrame(data)

Nulls

  First Name Last Name Hogwarts House   Age
0      Harry    Potter     Gryffindor  18.0
1   Hermione   Granger     Gryffindor  17.0
2        Ron   Weasley     Gryffindor   NaN
3      Draco    Malfoy            NaN  16.0
4       Luna       NaN      Ravenclaw  16.0
5        NaN  Lovegood     Gryffindor  18.0
6        NaN       NaN            NaN   NaN

In [55]:
Nulls.dropna()

  First Name Last Name Hogwarts House   Age
0      Harry    Potter     Gryffindor  18.0
1   Hermione   Granger     Gryffindor  17.0

In [56]:
Nulls.dropna(subset = ['Age'])

  First Name Last Name Hogwarts House   Age
0      Harry    Potter     Gryffindor  18.0
1   Hermione   Granger     Gryffindor  17.0
3      Draco    Malfoy            NaN  16.0
4       Luna       NaN      Ravenclaw  16.0
5        NaN  Lovegood     Gryffindor  18.0

In [58]:
Nulls.dropna(how = 'all')

  First Name Last Name Hogwarts House   Age
0      Harry    Potter     Gryffindor  18.0
1   Hermione   Granger     Gryffindor  17.0
2        Ron   Weasley     Gryffindor   NaN
3      Draco    Malfoy            NaN  16.0
4       Luna       NaN      Ravenclaw  16.0
5        NaN  Lovegood     Gryffindor  18.0

In [60]:
 Nulls['Age'].fillna(Nulls['Age'].mean())

0    18.0
1    17.0
2    17.0
3    16.0
4    16.0
5    18.0
6    17.0
Name: Age, dtype: float64

In [64]:
Nulls.replace(np.nan, 'Unknown')

  First Name Last Name Hogwarts House      Age
0      Harry    Potter     Gryffindor     18.0
1   Hermione   Granger     Gryffindor     17.0
2        Ron   Weasley     Gryffindor  Unknown
3      Draco    Malfoy        Unknown     16.0
4       Luna   Unknown      Ravenclaw     16.0
5    Unknown  Lovegood     Gryffindor     18.0
6    Unknown   Unknown        Unknown  Unknown

In [65]:
data = {
    'First name': ['Harry', 'Harry', 'Hermione', 'Hermione', 'Ron', 'Ron', 'Draco', 'Draco', 'Luna', 'Luna', 'Neville', 'Neville', 'Ginny', 'Ginny', 'Fred', 'Fred', 'George', 'George', 'Cho', 'Cho', 'Cedric', 'Cedric', 'Sirius', 'Sirius', 'Remus', 'Remus'],
    'Last name': ['Potter', np.nan, 'Granger', 'Granger', 'Weasley', 'Weasley', 'Malfoy', 'Malfoy', 'Lovegood', 'Lovegood', 'Longbottom', 'Longbottom', 'Weasley', 'Weasley', 'Weasley', 'Weasley', 'Weasley', 'Weasley', 'Chang', 'Chang', 'Diggory', 'Diggory', 'Black', 'Black', 'Lupin', 'Lupin'],
    'Hogwarts house': ['Gryffindor', 'Gryffindor', 'Gryffindor', 'Gryffindor', np.nan, 'Gryffindor', 'Slytherin', 'Slytherin', 'Ravenclaw', 'Ravenclaw', 'Gryffindor', 'Gryffindor', 'Gryffindor', 'Gryffindor', 'Gryffindor', 'Gryffindor', 'Gryffindor', 'Gryffindor', 'Ravenclaw', 'Ravenclaw', 'Hufflepuff', 'Hufflepuff', 'Gryffindor', 'Gryffindor', 'Gryffindor', 'Gryffindor'],
    'Transaction_ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, np.nan, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
    'Transaction_amount': [50, 75, 30, 20, 45, 60, 55, 80, 65, 70, 40, 85, 90, 55, 60, 75, 80, 35, 40, 95, 50, 65, 70, 25, 30, 45]
}

df = pd.DataFrame(data)
df

   First name   Last name Hogwarts house  Transaction_ID  Transaction_amount
0       Harry      Potter     Gryffindor             1.0                  50
1       Harry         NaN     Gryffindor             2.0                  75
2    Hermione     Granger     Gryffindor             3.0                  30
3    Hermione     Granger     Gryffindor             4.0                  20
4         Ron     Weasley            NaN             5.0                  45
5         Ron     Weasley     Gryffindor             6.0                  60
6       Draco      Malfoy      Slytherin             7.0                  55
7       Draco      Malfoy      Slytherin             8.0                  80
8        Luna    Lovegood      Ravenclaw             9.0                  65
9        Luna    Lovegood      Ravenclaw            10.0                  70
10    Neville  Longbottom     Gryffindor            11.0                  40
11    Neville  Longbottom     Gryffindor            12.0                  85
12      Ginny     Weasley     Gryffindor            13.0                  90
13      Ginny     Weasley     Gryffindor            14.0                  55
14       Fred     Weasley     Gryffindor             NaN                  60
15       Fred     Weasley     Gryffindor            16.0                  75
16     George     Weasley     Gryffindor            17.0                  80
17     George     Weasley     Gryffindor            18.0                  35
18        Cho       Chang      Ravenclaw            19.0                  40
19        Cho       Chang      Ravenclaw            20.0                  95
20     Cedric     Diggory     Hufflepuff            21.0                  50
21     Cedric     Diggory     Hufflepuff            22.0                  65
22     Sirius       Black     Gryffindor            23.0                  70
23     Sirius       Black     Gryffindor            24.0                  25
24      Remus       Lupin     Gryffindor            25.0                  30
25      Remus       Lupin     Gryffindor            26.0                  45

In [70]:
df['Last name'] = df['Last name'].fillna(df.groupby(['First name','Hogwarts house'])['Last name'].transform('first'))

In [71]:
df

   First name   Last name Hogwarts house  Transaction_ID  Transaction_amount
0       Harry      Potter     Gryffindor             1.0                  50
1       Harry      Potter     Gryffindor             2.0                  75
2    Hermione     Granger     Gryffindor             3.0                  30
3    Hermione     Granger     Gryffindor             4.0                  20
4         Ron     Weasley            NaN             5.0                  45
5         Ron     Weasley     Gryffindor             6.0                  60
6       Draco      Malfoy      Slytherin             7.0                  55
7       Draco      Malfoy      Slytherin             8.0                  80
8        Luna    Lovegood      Ravenclaw             9.0                  65
9        Luna    Lovegood      Ravenclaw            10.0                  70
10    Neville  Longbottom     Gryffindor            11.0                  40
11    Neville  Longbottom     Gryffindor            12.0                  85
12      Ginny     Weasley     Gryffindor            13.0                  90
13      Ginny     Weasley     Gryffindor            14.0                  55
14       Fred     Weasley     Gryffindor             NaN                  60
15       Fred     Weasley     Gryffindor            16.0                  75
16     George     Weasley     Gryffindor            17.0                  80
17     George     Weasley     Gryffindor            18.0                  35
18        Cho       Chang      Ravenclaw            19.0                  40
19        Cho       Chang      Ravenclaw            20.0                  95
20     Cedric     Diggory     Hufflepuff            21.0                  50
21     Cedric     Diggory     Hufflepuff            22.0                  65
22     Sirius       Black     Gryffindor            23.0                  70
23     Sirius       Black     Gryffindor            24.0                  25
24      Remus       Lupin     Gryffindor            25.0                  30
25      Remus       Lupin     Gryffindor            26.0                  45

In [73]:
df['Transaction_ID'] = df['Transaction_ID'].fillna(df['Transaction_ID'].ffill().mean())

In [74]:
df

   First name   Last name Hogwarts house  Transaction_ID  Transaction_amount
0       Harry      Potter     Gryffindor        1.000000                  50
1       Harry      Potter     Gryffindor        2.000000                  75
2    Hermione     Granger     Gryffindor        3.000000                  30
3    Hermione     Granger     Gryffindor        4.000000                  20
4         Ron     Weasley            NaN        5.000000                  45
5         Ron     Weasley     Gryffindor        6.000000                  60
6       Draco      Malfoy      Slytherin        7.000000                  55
7       Draco      Malfoy      Slytherin        8.000000                  80
8        Luna    Lovegood      Ravenclaw        9.000000                  65
9        Luna    Lovegood      Ravenclaw       10.000000                  70
10    Neville  Longbottom     Gryffindor       11.000000                  40
11    Neville  Longbottom     Gryffindor       12.000000                  85
12      Ginny     Weasley     Gryffindor       13.000000                  90
13      Ginny     Weasley     Gryffindor       14.000000                  55
14       Fred     Weasley     Gryffindor       13.461538                  60
15       Fred     Weasley     Gryffindor       16.000000                  75
16     George     Weasley     Gryffindor       17.000000                  80
17     George     Weasley     Gryffindor       18.000000                  35
18        Cho       Chang      Ravenclaw       19.000000                  40
19        Cho       Chang      Ravenclaw       20.000000                  95
20     Cedric     Diggory     Hufflepuff       21.000000                  50
21     Cedric     Diggory     Hufflepuff       22.000000                  65
22     Sirius       Black     Gryffindor       23.000000                  70
23     Sirius       Black     Gryffindor       24.000000                  25
24      Remus       Lupin     Gryffindor       25.000000                  30
25      Remus       Lupin     Gryffindor       26.000000                  45