In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("C:/Users/tcaal/Desktop/Learning Python/Data/banking.csv",
                 encoding = 'ISO-8859-1')

In [4]:
df.head()

,age,job,marital,education,default,outstanding_balance,housing_loan,personal_loan
0,58,management,married,tertiary,no,2143,yes,no
1,44,technician,single,secondary,no,29,yes,no
2,33,entrepreneur,married,secondary,no,2,yes,yes
3,47,blue-collar,married,unknown,no,1506,yes,no
4,33,unknown,single,unknown,no,1,no,no

In [5]:
df.groupby('job')['age'].mean() # Groups by the job, and then selects the age and takes the mean

job
admin.           39.289886
blue-collar      40.044081
entrepreneur     42.190989
housemaid        46.415323
management       40.449567
retired          61.626767
self-employed    40.484484
services         38.740250
student          26.542644
technician       39.314598
unemployed       40.961627
unknown          47.593750
Name: age, dtype: float64

In [11]:
df.query('education == "tertiary" & housing_loan == "yes"').groupby('marital')['age'].mean() # Run a sort through a query too

marital
divorced    44.220452
married     40.195444
single      33.892529
Name: age, dtype: float64

In [12]:
df.groupby('job').describe() # describe provides stats

                  age                                                      \
                count       mean        std   min   25%   50%   75%   max
job
admin.         5171.0  39.289886   9.365483  20.0  32.0  38.0  46.0  75.0
blue-collar    9732.0  40.044081   9.025888  20.0  33.0  39.0  47.0  75.0
entrepreneur   1487.0  42.190989   9.114486  21.0  35.0  41.0  49.0  84.0
housemaid      1240.0  46.415323  10.477275  22.0  38.0  47.0  55.0  83.0
management     9458.0  40.449567   9.383415  21.0  33.0  38.0  48.0  81.0
retired        2264.0  61.626767   9.535329  24.0  56.0  59.0  67.0  95.0
self-employed  1579.0  40.484484   9.656075  22.0  33.0  39.0  48.0  76.0
services       4154.0  38.740250   9.041371  20.0  32.0  37.0  46.0  69.0
student         938.0  26.542644   4.842536  18.0  23.0  26.0  29.0  48.0
technician     7597.0  39.314598   8.939944  21.0  32.0  37.0  46.0  71.0
unemployed     1303.0  40.961627   9.777010  21.0  33.0  40.0  48.0  66.0
unknown         288.0  47.593750  10.775095  25.0  41.0  47.0  55.0  82.0

              outstanding_balance                                            \
                            count         mean          std     min     25%
job
admin.                     5171.0  1135.838909  2641.962686 -1601.0   63.00
blue-collar                9732.0  1078.826654  2240.523208 -8019.0   55.00
entrepreneur               1487.0  1521.470074  4153.442626 -2082.0   44.50
housemaid                  1240.0  1392.395161  2984.692098 -1941.0   57.75
management                 9458.0  1763.616832  3822.965605 -6847.0   98.00
retired                    2264.0  1984.215106  4397.044177 -1598.0  164.50
self-employed              1579.0  1647.970868  3684.259573 -3313.0  120.00
services                   4154.0   997.088108  2164.493505 -2122.0   35.00
student                     938.0  1388.060768  2441.703526  -679.0  148.25
technician                 7597.0  1252.632092  2548.544019 -2827.0   61.00
unemployed                 1303.0  1521.745971  3144.666754 -1270.0   94.00
unknown                     288.0  1772.357639  2970.288559  -295.0  170.75


                 50%      75%       max
job
admin.         396.0  1203.00   64343.0
blue-collar    388.0  1203.00   66653.0
entrepreneur   352.0  1341.00   59649.0
housemaid      406.0  1382.75   45141.0
management     572.0  1825.00  102127.0
retired        787.0  2309.00   81204.0
self-employed  526.0  1603.50   52587.0
services       339.5  1071.75   57435.0
student        502.0  1579.75   24025.0
technician     421.0  1327.00   45248.0
unemployed     529.0  1603.50   44134.0
unknown        677.0  2165.50   19706.0

In [14]:
df.groupby('education')['outstanding_balance'].min().sort_values(ascending = True)

education
secondary   -8019
tertiary    -6847
primary     -2604
unknown     -1445
Name: outstanding_balance, dtype: int64

In [15]:
df.groupby('education')['outstanding_balance'].count().sort_values(ascending = True)

education
unknown       1857
primary       6851
tertiary     13301
secondary    23202
Name: outstanding_balance, dtype: int64

In [16]:
df.groupby('education')['outstanding_balance'].mean().sort_values(ascending = True)

education
secondary    1154.880786
primary      1250.949934
unknown      1526.754443
tertiary     1758.416435
Name: outstanding_balance, dtype: float64

In [17]:
df.groupby('education').agg({'outstanding_balance':['median','mean','count']})

          outstanding_balance
                       median         mean  count
education
primary                 403.0  1250.949934   6851
secondary               392.0  1154.880786  23202
tertiary                577.0  1758.416435  13301
unknown                 568.0  1526.754443   1857

In [26]:
stats = df.groupby('education').agg({'outstanding_balance':['median','mean','count','sum']})

In [27]:
stats['avg'] = stats['outstanding_balance']['sum']/stats['outstanding_balance']['count']

In [28]:
stats

          outstanding_balance                                        avg
                       median         mean  count       sum
education
primary                 403.0  1250.949934   6851   8570258  1250.949934
secondary               392.0  1154.880786  23202  26795544  1154.880786
tertiary                577.0  1758.416435  13301  23388697  1758.416435
unknown                 568.0  1526.754443   1857   2835183  1526.754443

In [ ]:
df.groupby(['job','marital'])['outstanding_balance'].mean() # Multiple Group by

job            marital
admin.         divorced     878.333333
               married     1281.409580
               single      1020.739005
blue-collar    divorced     820.806667
               married     1113.165901
               single      1056.105263
entrepreneur   divorced    1155.983240
               married     1643.387850
               single      1248.235294
housemaid      divorced    1573.222826
               married     1248.173246
               single      2074.743056
management     divorced    1618.073807
               married     1828.159444
               single      1700.219545
retired        divorced    1507.835294
               married     2140.098787
               single      1360.388889
self-employed  divorced    2426.350000
               married     1644.948640
               single      1410.365471
services       divorced     834.304189
               married     1088.847528
               single       887.324708
student        divorced    1101.000000
               married     1164.796296
               single      1403.753986
technician     divorced     924.048649
               married     1307.399556
               single      1283.938168
unemployed     divorced    1409.643275
               married     1568.632011
               single      1484.079800
unknown        divorced    1706.294118
               married     1788.128079
               single      1741.794118
Name: outstanding_balance, dtype: float64

In [31]:
# By job

df[df['job'] == 'retired'].groupby(['job','marital'])['outstanding_balance'].mean()

job      marital
retired  divorced    1507.835294
         married     2140.098787
         single      1360.388889
Name: outstanding_balance, dtype: float64

In [33]:
# Put into df

df2 = df.groupby(['education','personal_loan'])['outstanding_balance'].mean()

In [36]:
new = df2.reset_index()

In [42]:
# Similar to SQL Windows function

df['average balance by job'] = df.groupby('job')['outstanding_balance'].transform('mean')

In [43]:
df

,age,job,marital,education,default,outstanding_balance,housing_loan,personal_loan,average balance by job
0,58,management,married,tertiary,no,2143,yes,no,1763.616832
1,44,technician,single,secondary,no,29,yes,no,1252.632092
2,33,entrepreneur,married,secondary,no,2,yes,yes,1521.470074
3,47,blue-collar,married,unknown,no,1506,yes,no,1078.826654
4,33,unknown,single,unknown,no,1,no,no,1772.357639
...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,1252.632092
45207,71,retired,divorced,primary,no,1729,no,no,1984.215106
45208,72,retired,married,secondary,no,5715,no,no,1984.215106
45209,57,blue-collar,married,secondary,no,668,no,no,1078.826654
45210,37,entrepreneur,married,secondary,no,2971,no,no,1521.470074

In [44]:
df['outstanding balance minus mean'] = df.groupby('job')['outstanding_balance'].transform(lambda x: x - x.mean())

# This lambda function will examine the 'x', in this case our variable outstanding balance, and then subtract the mean of x so we get a difference

In [45]:
df

,age,job,marital,education,default,outstanding_balance,housing_loan,personal_loan,average balance by job,outstanding balance minus mean
0,58,management,married,tertiary,no,2143,yes,no,1763.616832,379.383168
1,44,technician,single,secondary,no,29,yes,no,1252.632092,-1223.632092
2,33,entrepreneur,married,secondary,no,2,yes,yes,1521.470074,-1519.470074
3,47,blue-collar,married,unknown,no,1506,yes,no,1078.826654,427.173346
4,33,unknown,single,unknown,no,1,no,no,1772.357639,-1771.357639
...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,1252.632092,-427.632092
45207,71,retired,divorced,primary,no,1729,no,no,1984.215106,-255.215106
45208,72,retired,married,secondary,no,5715,no,no,1984.215106,3730.784894
45209,57,blue-collar,married,secondary,no,668,no,no,1078.826654,-410.826654
45210,37,entrepreneur,married,secondary,no,2971,no,no,1521.470074,1449.529926

In [49]:
# can filter too

df['average balance for having housing loan'] = df[df['housing_loan'] == 'yes'].groupby('job')['outstanding_balance'].transform('mean')

In [50]:
df

,age,job,marital,education,default,outstanding_balance,housing_loan,personal_loan,average balance by job,outstanding balance minus mean,average balance for having housing loan
0,58,management,married,tertiary,no,2143,yes,no,1763.616832,379.383168,1610.207567
1,44,technician,single,secondary,no,29,yes,no,1252.632092,-1223.632092,1205.064156
2,33,entrepreneur,married,secondary,no,2,yes,yes,1521.470074,-1519.470074,1278.798619
3,47,blue-collar,married,unknown,no,1506,yes,no,1078.826654,427.173346,978.860528
4,33,unknown,single,unknown,no,1,no,no,1772.357639,-1771.357639,NaN
...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,1252.632092,-427.632092,NaN
45207,71,retired,divorced,primary,no,1729,no,no,1984.215106,-255.215106,NaN
45208,72,retired,married,secondary,no,5715,no,no,1984.215106,3730.784894,NaN
45209,57,blue-collar,married,secondary,no,668,no,no,1078.826654,-410.826654,NaN
45210,37,entrepreneur,married,secondary,no,2971,no,no,1521.470074,1449.529926,NaN