In [1]:
import pandas as pd

In [9]:
df = pd.read_csv("C:/Users/tcaal/Desktop/Learning Python/Data/WorldContinents.csv",
                 encoding = 'ISO-8859-1')

In [11]:
df.head()

  continent       sub_region         country code_3   Unnamed: 4
0      Asia    Southern Asia     Afghanistan    AFG   6,900,000
1    Europe  Northern Europe   Åland Islands    ALA   5,500,000
2    Europe  Southern Europe         Albania    ALB   3,300,000
3    Africa  Northern Africa         Algeria    DZA   9,500,000
4   Oceania        Polynesia  American Samoa    ASM      55,000

In [6]:
df2 = pd.read_csv("C:/Users/tcaal/Desktop/Learning Python/Data/WorldContinents.csv",
                 encoding = 'ISO-8859-1',
                 index_col = 'country')

In [7]:
df2.head()

               continent       sub_region code_3   Unnamed: 4
country
Afghanistan         Asia    Southern Asia    AFG   6,900,000
Åland Islands     Europe  Northern Europe    ALA   5,500,000
Albania           Europe  Southern Europe    ALB   3,300,000
Algeria           Africa  Northern Africa    DZA   9,500,000
American Samoa   Oceania        Polynesia    ASM      55,000

In [8]:
df.set_index('country')

                  continent       sub_region code_3     Unnamed: 4
country
Afghanistan            Asia    Southern Asia    AFG     6,900,000
Åland Islands        Europe  Northern Europe    ALA     5,500,000
Albania              Europe  Southern Europe    ALB     3,300,000
Algeria              Africa  Northern Africa    DZA     9,500,000
American Samoa      Oceania        Polynesia    ASM        55,000
...                     ...              ...    ...            ...
Wallis and Futuna   Oceania        Polynesia    WLF    15,900,000
Western Sahara       Africa  Northern Africa    ESH       597,000
Yemen                  Asia     Western Asia    YEM     5,500,000
Zambia               Africa   Eastern Africa    ZMB   213,000,000
Zimbabwe             Africa   Eastern Africa    ZWE    19,100,000

[240 rows x 4 columns]

In [12]:
df.set_index(['country'], inplace = True)

In [16]:
df.iloc[0] # Number location
df.loc['Zambia'] # Named based on new index

continent             Africa
sub_region    Eastern Africa
code_3                   ZMB
Unnamed: 4      213,000,000
Name: Zambia, dtype: str

In [27]:
df.reset_index(inplace = True)

In [ ]:
df_new = df.set_index(['country','sub_region']) # Multi Level Indexing

In [19]:
df_new.head()

                               continent code_3   Unnamed: 4
country        sub_region
Afghanistan    Southern Asia        Asia    AFG   6,900,000
Åland Islands  Northern Europe    Europe    ALA   5,500,000
Albania        Southern Europe    Europe    ALB   3,300,000
Algeria        Northern Africa    Africa    DZA   9,500,000
American Samoa Polynesia         Oceania    ASM      55,000

In [ ]:
df_new.loc['Albania','Southern Europe'] # Drill Down

continent          Europe
code_3                ALB
Unnamed: 4     3,300,000
Name: (Albania, Southern Europe), dtype: str

In [23]:
df_new.loc['Afghanistan']

              continent code_3   Unnamed: 4
sub_region
Southern Asia      Asia    AFG   6,900,000

In [ ]:
df.iloc[0,0] # location 0,0 after indexes are placed

'Afghanistan'

In [26]:
df.set_index(['continent','sub_region']).sort_index(ascending = True)

                                    country code_3     Unnamed: 4
continent sub_region
Africa    Eastern Africa            Burundi    BDI   128,000,000
          Eastern Africa            Comoros    COM       870,000
          Eastern Africa           Djibouti    DJI       988,000
          Eastern Africa            Eritrea    ERI     5,100,000
          Eastern Africa           Ethiopia    ETH    16,700,000
...                                     ...    ...            ...
Oceania   Polynesia                   Samoa    WSM    26,000,000
          Polynesia                 Tokelau    TKL     2,000,000
          Polynesia                   Tonga    TON    11,500,000
          Polynesia                  Tuvalu    TUV    15,000,000
          Polynesia       Wallis and Futuna    WLF    15,900,000

[240 rows x 3 columns]

In [ ]:
df.pivot(index = 'country',
         columns = 'continent',
         values = 'Unnamed: 4') # Appears to be like pivot_wider

continent              Africa Americas         Asia       Europe   Oceania
country
Afghanistan               NaN      NaN   6,900,000           NaN       NaN
Albania                   NaN      NaN          NaN   3,300,000        NaN
Algeria            9,500,000       NaN          NaN          NaN       NaN
American Samoa            NaN      NaN          NaN          NaN   55,000
Andorra                   NaN      NaN          NaN      77,000        NaN
...                       ...      ...          ...          ...       ...
Western Sahara       597,000       NaN          NaN          NaN       NaN
Yemen                     NaN      NaN   5,500,000           NaN       NaN
Zambia           213,000,000       NaN          NaN          NaN       NaN
Zimbabwe          19,100,000       NaN          NaN          NaN       NaN
Åland Islands             NaN      NaN          NaN   5,500,000        NaN

[240 rows x 5 columns]