In [1]:
import pandas as pd

In [2]:
data1 = {
    'employee_id': [1, 2, 3, 4, 5, 6, 7, 8],
    'name': ['Michael Scott', 'Jim Halpert', 'Pam Beesly', 'Dwight Schrute', 'Angela Martin', 'Kevin Malone', 'Oscar Martinez', 'Stanley Hudson'],
    'job_title': ['Regional Manager', 'Sales Representative', 'Receptionist', 'Assistant to the Regional Manager', 'Head of Accounting', 'Accountant', 'Accountant', 'Sales Representative'],
    'salary': [100000, 60000, 55000, 65000, 60000, 55000, 55000, 60000]
}

df1 = pd.DataFrame(data1)

data2 = {
    'employee_id': [1, 2, 3, 5, 6, 7, 8, 9],
    'name': ['Michael Scott', 'Jim Halpert', 'Pam Beesly', 'Angela Martin', 'Kevin Malone', 'Oscar Martinez', 'Stanley Hudson', 'Phyllis Vance'],
    'department': ['Management', 'Sales', 'Reception', 'Accounting', 'Accounting', 'Accounting', 'Sales', 'Sales']
}

df2 = pd.DataFrame(data2)

In [ ]:
df1.merge(df2) # Inner Joins

   employee_id            name             job_title  salary  department
0            1   Michael Scott      Regional Manager  100000  Management
1            2     Jim Halpert  Sales Representative   60000       Sales
2            3      Pam Beesly          Receptionist   55000   Reception
3            5   Angela Martin    Head of Accounting   60000  Accounting
4            6    Kevin Malone            Accountant   55000  Accounting
5            7  Oscar Martinez            Accountant   55000  Accounting
6            8  Stanley Hudson  Sales Representative   60000       Sales

In [6]:
df1.merge(df2, 
          how = 'inner',
          on = 'employee_id')

,employee_id,name_x,job_title,salary,name_y,department
0,1,Michael Scott,Regional Manager,100000,Michael Scott,Management
1,2,Jim Halpert,Sales Representative,60000,Jim Halpert,Sales
2,3,Pam Beesly,Receptionist,55000,Pam Beesly,Reception
3,5,Angela Martin,Head of Accounting,60000,Angela Martin,Accounting
4,6,Kevin Malone,Accountant,55000,Kevin Malone,Accounting
5,7,Oscar Martinez,Accountant,55000,Oscar Martinez,Accounting
6,8,Stanley Hudson,Sales Representative,60000,Stanley Hudson,Sales

In [10]:
pd.merge(df1,df2[['employee_id','department']],
         on = 'employee_id',
         how = 'inner')

   employee_id            name             job_title  salary  department
0            1   Michael Scott      Regional Manager  100000  Management
1            2     Jim Halpert  Sales Representative   60000       Sales
2            3      Pam Beesly          Receptionist   55000   Reception
3            5   Angela Martin    Head of Accounting   60000  Accounting
4            6    Kevin Malone            Accountant   55000  Accounting
5            7  Oscar Martinez            Accountant   55000  Accounting
6            8  Stanley Hudson  Sales Representative   60000       Sales

In [12]:
pd.merge(df1,df2,
         on = 'employee_id',
         how = 'inner',
         suffixes = ('_left','_right'),
         indicator = True)

,employee_id,name_left,job_title,salary,name_right,department,_merge
0,1,Michael Scott,Regional Manager,100000,Michael Scott,Management,both
1,2,Jim Halpert,Sales Representative,60000,Jim Halpert,Sales,both
2,3,Pam Beesly,Receptionist,55000,Pam Beesly,Reception,both
3,5,Angela Martin,Head of Accounting,60000,Angela Martin,Accounting,both
4,6,Kevin Malone,Accountant,55000,Kevin Malone,Accounting,both
5,7,Oscar Martinez,Accountant,55000,Oscar Martinez,Accounting,both
6,8,Stanley Hudson,Sales Representative,60000,Stanley Hudson,Sales,both